### ISSUE TITLE
cannot transcribe subtitles

### ISSUE THREAD

**Issue by Vader77Darth** [tin2tin/Subtitle_Editor#10]
It fails to transcribe subtitles
Requirement already satisfied: mpmath>=0.19 in c:\users\vader\appdata\roaming\python\python311\site-packages (from sympy->torch) (1.3.0)
Traceback (most recent call last):
  File "C:\Users\Vader\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\Subtitle_Editor-main\__init__.py", line 625, in execute
    import_module(self, "whisper", "git+https://github.com/openai/whisper.git") # "openai_whisper"):#
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vader\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\Subtitle_Editor-main\__init__.py", line 133, in import_module
    exec("import " + module)
  File "<string>", line 1, in <module>
  File "C:\Users\Vader\AppData\Roaming\Python\Python311\site-packages\whisper\__init__.py", line 8, in <module>
    import torch
  File "C:\Users\Vader\AppData\Roaming\Python\Python311\site-packages\torch\__init__.py", line 141, in <module>
    raise err
OSError: [WinError 126] The specified module could not be found. Error loading "C:\Users\Vader\AppData\Roaming\Python\Python311\site-packages\torch\lib\shm.dll" or one of its dependencies.
Error: Python: Traceback (most recent call last):
  File "C:\Users\Vader\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\Subtitle_Editor-main\__init__.py", line 133, in import_module
    exec("import " + module)
  File "<string>", line 1, in <module>
  File "C:\Users\Vader\AppData\Roaming\Python\Python311\site-packages\whisper\__init__.py", line 8, in <module>
    import torch
  File "C:\Users\Vader\AppData\Roaming\Python\Python311\site-packages\torch\__init__.py", line 141, in <module>
    raise err
OSError: [WinError 126] The specified module could not be found. Error loading "C:\Users\Vader\AppData\Roaming\Python\Python311\site-packages\torch\lib\shm.dll" or one of its dependencies.

Still doesn't work when launched as administrator.

https://github.com/tin2tin/Subtitle_Editor/assets/87441738/4b177499-efcf-48c3-b0fc-5414d3f6531c

**Comment by tin2tin** [comment]
The dependencies installation has since been reworked, so closing this now. Feel free to open a new report if it still fails the same way.
