### ISSUE TITLE
AttributeError: module 'ctypes' has no attribute 'windll'

### ISSUE THREAD

**Issue by nerviZida** [tin2tin/Subtitle_Editor#3]
In Linux Trisquel 10

Python: Traceback (most recent call last):
  File "/home/trisquel/.config/blender/3.5/scripts/addons/subtitle_editor-main/__init__.py", line 593, in execute
    import_module(self, "torch", "torch==2.0.0")
  File "/home/trisquel/.config/blender/3.5/scripts/addons/subtitle_editor-main/__init__.py", line 126, in import_module
    show_system_console(True)
  File "/home/trisquel/.config/blender/3.5/scripts/addons/subtitle_editor-main/__init__.py", line 84, in show_system_console
    ctypes.windll.user32.ShowWindow(
AttributeError: module 'ctypes' has no attribute 'windll'

And in Linux PopOs

bpy.ops.text.transcribe()
Python: Traceback (most recent call last):
  File "/home/a/.config/blender/3.5/scripts/addons/subtitle_editor-main/__init__.py", line 593, in execute
    import_module(self, "torch", "torch==2.0.0")
  File "/home/a/.config/blender/3.5/scripts/addons/subtitle_editor-main/__init__.py", line 126, in import_module
    show_system_console(True)
  File "/home/a/.config/blender/3.5/scripts/addons/subtitle_editor-main/__init__.py", line 84, in show_system_console
    ctypes.windll.user32.ShowWindow(
AttributeError: module 'ctypes' has no attribute 'windll'

**Comment by tin2tin** [comment]
As I'm on Windows and have no way to check if an installation works on Linux, I need help from someone on Linux to try to install it. I can then afterwards correct the code accordingly.

I've tried to update the code, so, tell me if this works for you, if not try this and let me know how it goes: 

If you feel up for it, first step is to uninstall torch. 
The easiest way is to install this add-on: https://github.com/amb/blender_pip/releases 
In the add-on properties, you type in torch and hit remove.
Then use this modelcard to find the install instruction. And then use the add-on to install the modules: https://pytorch.org/get-started/locally/
And tell me which one works for you.

**Comment by tin2tin** [comment]
Closing, as I can't support the add-on on Linux.
