### ISSUE TITLE
file not found error in 3.6

### ISSUE THREAD

**Issue by alesSowa** [tin2tin/Subtitle_Editor#4]
Greetings,
experiencing this error on Transcribe in blender 3.6: 

![image](https://github.com/tin2tin/Subtitle_Editor/assets/42345101/3f2a249c-8ca1-49d4-98ed-cc1996b922e5)
I tried running blender also as administrator, but it is the same.

**Comment by tin2tin** [comment]
If you select the audio file, in the sidebar go to Source and open the path(with folder names), open the sidebar of the file browser and uncheck relative path, does it work then?

If not, are there any messages about missing modules?

**Comment by alesSowa** [comment]
hey, just tried, used absolute path, got the same error.

**Comment by tin2tin** [comment]
^ Is this the full text ? 
(It works fine here, so I can't reproduce)

**Comment by alesSowa** [comment]
this is the full text. also tried on the other machine, same error. 
could you point me to the part of code that is trying to access the file? what file?

**Comment by tin2tin** [comment]
I updated the installation instructions. Try to follow them. 

If there are errors on missing modules, then use this to install/remove/check installed modules: https://github.com/amb/blender_pip

**Comment by alesSowa** [comment]
followed the instructions, saw in this pip package that I have all the needed modules installed. got the same error.
sound paths look ok. tried also different models, but getting the same error once downloaded.

**Comment by tin2tin** [comment]
wild shot: does your path contain space or unusual characters?

**Comment by tin2tin** [comment]
Are there any spaces or anything else in the path name, which could be misinterpreted? 
Could you try with a file with a simple name+path?

**Comment by tin2tin** [comment]
Closing this due to inactivity.

**Comment by Clutche** [comment]
Hello! First off, love the add-on! However I've been experiencing the same issue as alesSowa. I attempted both suggestions (uncheck relative path & setting simple path (without spaces) to video) above to no avail. Have you come across another similar issue since the inactivity? Any other suggestions?

Few callouts: 
Blender 4.0.2
I installed blender through Steam to leverage auto-updates. Not sure if could cause potential issues.
Python Module Manager add-on is installed

Simple path: "C:\Users\userx\Documents\Tube\tootsie_pop.mp4"

```Please wait. Checking torch & whisper modules...
Looking in indexes: https://download.pytorch.org/whl/cu118
Requirement already satisfied: torch in c:\users\userx\appdata\roaming\python\python310\site-packages (2.2.1+cu118)
Requirement already satisfied: filelock in c:\users\userx\appdata\roaming\python\python310\site-packages (from torch) (3.9.0)
Requirement already satisfied: typing-extensions>=4.8.0 in c:\users\userx\appdata\roaming\python\python310\site-packages (from torch) (4.8.0)
Requirement already satisfied: sympy in c:\users\userx\appdata\roaming\python\python310\site-packages (from torch) (1.12)
Requirement already satisfied: networkx in c:\users\userx\appdata\roaming\python\python310\site-packages (from torch) (3.2.1)
Requirement already satisfied: jinja2 in c:\users\userx\appdata\roaming\python\python310\site-packages (from torch) (3.1.2)
Requirement already satisfied: fsspec in c:\users\userx\appdata\roaming\python\python310\site-packages (from torch) (2023.4.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\userx\appdata\roaming\python\python310\site-packages (from jinja2->torch) (2.1.3)
Requirement already satisfied: mpmath>=0.19 in c:\users\userx\appdata\roaming\python\python310\site-packages (from sympy->torch) (1.3.0)
Please wait. Processing file...
Traceback (most recent call last):
  File "C:\Users\userx\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\Subtitle_Editor-main\__init__.py", line 653, in execute
    result = model.transcribe(sound_path)
  File "C:\Users\userx\AppData\Roaming\Python\Python310\site-packages\whisper\transcribe.py", line 133, in transcribe
    mel = log_mel_spectrogram(audio, model.dims.n_mels, padding=N_SAMPLES)
  File "C:\Users\userx\AppData\Roaming\Python\Python310\site-packages\whisper\audio.py", line 140, in log_mel_spectrogram
    audio = load_audio(audio)
  File "C:\Users\userx\AppData\Roaming\Python\Python310\site-packages\whisper\audio.py", line 58, in load_audio
    out = run(cmd, capture_output=True, check=True).stdout
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.0\python\lib\subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.0\python\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.0\python\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
Error: Python: Traceback (most recent call last):
  File "C:\Users\userx\AppData\Roaming\Python\Python310\site-packages\whisper\audio.py", line 58, in load_audio
    out = run(cmd, capture_output=True, check=True).stdout
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.0\python\lib\subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.0\python\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.0\python\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
